# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Nest.JS

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches:
      - '**'

jobs:
  setup-and-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Node.JS setup
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - id: yarn-cache
        name: Setup packages cache
        uses: actions/cachev3.2.4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: yarn build

      - name: Eslint
        run: yarn lint
        
      - name: Test with coverage
        run: yarn test --coverage

  deploy:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    needs: setup-and-build
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Deploy to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: ""
          process_type: web
